src/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('curso.urls')),
]

src/curso/urls.py
from django.urls import path

from .views import (
    about,
    index,
    curso_list,
    comision_list,
    alumno_list,
    curso_create,
    comision_create,
    alumno_create,
)

app_name = "curso"

urlpatterns = [
    path("", index, name="index"),
    path("about/", about, name="about"),
    path("curso/list/", curso_list, name="curso_list"),
    path("curso/create/", curso_create, name="curso_create"),
    path("comision/list/", comision_list, name="comision_list"),
    path("comision/create/", comision_create, name="comision_create"),
    path("alumno/list", alumno_list, name="alumno_list"),
    path("alumno/create/", alumno_create, name="alumno_create"),
]

src/curso/models.py
from django.db import models

class Curso(models.Model):
    nombre = models.CharField(max_length=255, unique=True)
    
    def __str__(self):
        return self.nombre

class Comision(models.Model):
    curso = models.ForeignKey(Curso, on_delete=models.SET_NULL, null=True)
    numero = models.PositiveBigIntegerField()
    fecha_inicio = models.DateField()
    def __str__(self):
        return f"{self.curso} -  {self.numero}"

class Alumno(models.Model):
    comision = models.ForeignKey(Comision, on_delete=models.SET_NULL, null=True)
    dni = models.IntegerField(unique=True)

src/curso/forms.py
from django import forms

from .models import Curso, Comision, Alumno

class CursoForm(forms.ModelForm):
    class Meta:
        model = Curso
        fields ="__all__"
        
class ComisionForm(forms.ModelForm):
    class Meta:
        model = Comision
        fields ="__all__"
        widgets = {
            'fecha_inicio': forms.DateInput(attrs={'type': 'date'})
        }
        
class AlumnoForm(forms.ModelForm):
    class Meta:
        model = Alumno
        fields ="__all__"

src/curso/views.py
from django.shortcuts import render, redirect

from .models import Curso, Comision, Alumno
from .forms import CursoForm, AlumnoForm, ComisionForm


# Create your views here.
def index(request):
    return render(request, 'curso/index.html')

def about(request):
    return render(request, 'curso/about.html')

def curso_list(request):
    query = Curso.objects.all()
    context = {"object_list": query}
    return render(request, 'curso/curso_list.html', context)

def curso_create(request):
    if request.method == "GET":
        form = CursoForm()
    if request.method == "POST":
        form = CursoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("curso:curso_list")
    return render(request, "curso/curso_form.html", {"form": form})

def comision_list(request):
    query = Comision.objects.all()
    context = {"object_list": query}
    return render(request, 'curso/comision_list.html', context)

def comision_create(request):
    if request.method == "GET":
        form = ComisionForm()
    if request.method == "POST":
        form = ComisionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("curso:comision_list")
    return render(request, "curso/comision_form.html", {"form": form})
def alumno_list(request):
    query = Alumno.objects.all()
    context = {"object_list": query}
    return render(request, 'curso/alumno_list.html', context)

def alumno_create(request):
    if request.method == "GET":
        form = AlumnoForm()
    if request.method == "POST":
        form = AlumnoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("curso:alumno_list")
    return render(request, "curso/alumno_form.html", {"form": form})

src/curso/templates/curso/about.html
{% extends 'curso/base.html' %}

{% block contenido %}
    <h1>Acerca de mi</h1>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nulla at expedita doloribus itaque cupiditate. Quod laborum voluptatibus ratione iusto illum expedita impedit eos reprehenderit ab. Consectetur sit voluptas officia dolores.</p>
{% endblock contenido %}

src/curso/templates/curso/alumno_form.html
{%extends 'curso/base.html'%}

{% block contenido %}
<h1>Crear Alumno</h1>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Guardar</button>
    </form>
{% endblock contenido %}<form action="" method="post"></form>

src/curso/templates/curso/alumno_list.html
{% extends 'curso/base.html' %}

{% block contenido %}
<h1>Lista de Alumnos</h1>
<a href="{% url 'curso:alumno_create' %}"><button>Crear Alumno</button></a>
<table>
  <thead>
    <tr>
      <th>Comisión</th>
      <th>DNI</th>
    </tr>
  </thead>
  <tbody>
    {% for object in object_list %}
    <tr>
      <td>{{ object.comision }}</td>
      <td>{{ object.dni }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<a href="{% url 'curso:index' %}"><button>Regresar al Inicio</button></a>
{% endblock contenido %}

src/curso/templates/curso/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mi escuela</title>
    <span class="pln">
    </span><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic"><span class="pln">
    </span><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css"><span class="pln">
    </span><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.4.1/milligram.css"><span class="pln">
    </span>
</head>
<body  style="text-align: center">
    {% block contenido %}
        
    {% endblock contenido %}
</body>
</html>

src/curso/templates/curso/comision_form.html
{%extends 'curso/base.html'%}

{% block contenido %}
<h1>Crear Comision</h1>

    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Guardar</button>
    </form>
{% endblock contenido %}<form action="" method="post"></form>

src/curso/templates/curso/comision_list.html
{% extends 'curso/base.html' %}

{% block contenido %}
    <h1>Lista de Comisiones</h1>
    <a href="{%url 'curso:comision_create'%}"><button>Crear Comision</button></a>
    <ul>
        {% for object in object_list  %}
            <p>{{object.curso}} | {{object.numero}} | {{object.fecha_inicio}}</p>
        {% endfor %}
    </ul>
    <a href="{% url 'curso:index' %}"><button>Regresar al Inicio</button></a>

{% endblock contenido %}

src/curso/templates/curso/curso_form.html
{%extends 'curso/base.html'%}

{% block contenido %}
<h1>Crear Curso</h1>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Guardar</button>
    </form>
{% endblock contenido %}<form action="" method="post"></form>

src/curso/templates/curso/curso_list.html
{% extends 'curso/base.html' %}

{% block contenido %}
    <h1>Lista de Cursos</h1>
    <a href="{% url 'curso:curso_create' %}"><button>Crear Curso</button></a>
    <ul>
        {% for object in object_list  %}
            <p>{{object.nombre}}</p>
        {% endfor %}
    </ul>
    <a href="{% url 'curso:index' %}"><button>Regresar al Inicio</button></a>

{% endblock contenido %}

src/curso/templates/curso/index.html
{% extends 'curso/base.html' %}

{% block contenido %}
<main>                                              
    <h1>Bienvenido</h1>
     <a href="{% url 'curso:curso_list' %}"> <button>Mostrar Cursos  </button> </a>
     <a href="{% url 'curso:comision_list' %}"><button>Mostrar Comision  </button></a>
     <a href="{% url 'curso:alumno_list' %}"><button>Mostrar Alumno  </button></a>
</main>
{% endblock contenido %}